### ISSUE TITLE
Min capacity parameter not working

### ISSUE THREAD

**Issue by daldwinc** [mutatrum/lnd_graph_crawl#1]
Hi - love the script. Thanks for publishing it.

I think the min capacity parameter is not working. If I specify 5, I still get many results below 1 BTC:

`$ node lnd_graph_crawl.js <mynode> 10 5 14 | grep "capacity:   0." | head
027cf99e95e346897a6f88212d5240fa790e3b4c97581bcffa354de10128998ce7  distance: 2  channels:   28  capacity:   0.88  2021-03-23  ln.vanovcan.net (bos 13333333 cap 306 cha 405 age 1069 gro 507 ava 798)
02d147d5b634e3ef558461f7571099ce4e2b04dd831d9d0f2c2ecbc1cd814cae20  distance: 2  channels:   55  capacity:   0.77  2021-03-23  Bitcoin_Discord (bos 8888888 cap 338 cha 198 age 3072 gro 676 ava 486)
02da0713ab1b12eeb01f212944a435077f39f1b767ee5c24b01cdb4b0b9377b66b  distance: 2  channels:   73  capacity:   0.87  2021-03-23  ln1-a.lightcore.co (bos 13333333 cap 307 cha 140 age 1158 gro 2087 ava 1829)
036d81bb87af589f949dec53af1b3121c84048d0913eb56945cbbb62c5cb4fcb6f  distance: 2  channels:   23  capacity:   0.31  2021-03-22  hirish-ln (bos 13333333 cap 630 cha 504 age 484 gro 506 ava 845)
03094b63a5ece2c363ab859952017f95bec7bd9e6975f0c8152f9eff83d0b045c2  distance: 2  channels:   34  capacity:   0.80  2021-03-22  KIWILAMB (bos 13333333 cap 330 cha 325 age 2574 gro 293 ava 430)
02e5067afb7be9470214acc10d7b3ebc39e84cd7de57d86cc3598514fa6d821229  distance: 2  channels:   48  capacity:   0.70  2021-03-23  HODLcat.com (bos 8888888 cap 357 cha 239 age 2058 gro 2877 ava 1398)
02c0a6e4f7e6d01edc5aa14f5445cd8c87c478ad1c72fcb8b594d4989cc2a1fa9e  distance: 2  channels:   15  capacity:   0.36  2021-03-23  bitcoin.grey.pw (bos 8888888 cap 591 cha 806 age 3783 gro 4423 ava 924)
028737303e12cb84643d1f0181812b559a56ef5d78b4c43d1cc0c1c1f17dc88722  distance: 2  channels:   60  capacity:   0.67  2021-03-23  ⚡The-Lightning-Ride⚡ (bos 8888888 cap 367 cha 184 age 4686 gro 965 ava 800)
035f209faaea75427949e3e6c1fc9edafbf751f08706506bb873fdc93ffc2d4e2c  distance: 2  channels:   13  capacity:   0.48  2021-03-22  tthm4 (bos 8888888 cap 481 cha 970 age 4408 gro 675 ava 760)
02db9c5c2d0e40d6ce8747255983be8b309fa7caa7f67a72bc30e94bdddb326edf  distance: 2  channels:   20  capacity:   0.59  2021-03-23  booz (bos 8888888 cap 398 cha 580 age 4134 gro 515 ava 3520)`

**Comment by mutatrum** [comment]
A node is always included if it's in the BOS score file. The idea behind this is that node on the BOS list are always good to connect to. It's a bit obscure, but it's on the readme:

> If export.json is supplied, a node that is in the BOS score file will always be shown.

You can skip this behavior by removing the BOS file.

**Comment by daldwinc** [comment]
Ah, you are correct. I renamed the export.json file and my results are looking better.
